### ISSUE TITLE
Cannot initialize project (Failed to find Apple developer teams)

### ISSUE THREAD

**Issue by chinedufn** [BrainiumLLC/cargo-mobile#25]
Hey.

Trying to give `cargo mobile init` a spin and running into the following:

`macOS Catalina 10.5.7` `Xcode 12.4`

```
cargo mobile init
Project name (rust-ios):
Stylized name (Rust Ios):
Domain (example.com):
Detected template packs:
  [0] bevy
  [1] bevy-demo
  [2] wgpu
  [3] winit
  Enter an index for a template pack above.
Template pack (0): 2
error: Failed to prompt for `apple` config
    Failed to find Apple developer teams: Missing X509 field: Nid(17)
```

---

For context, I haven't used Xcode for much so I may have un-configured Xcode settings that an iOS developer would typically be expected to have.

**Comment by francesca64** [comment]
Thanks for reporting this! Developer team detection is definitely something I feel hasn't been tested enough.

It looks like whatever development team cargo-mobile is detecting doesn't have the "Organization" field. You can confirm this by opening Keychain.app, finding your development team's certificate (the keyword will be either "developer" or "development"), double-clicking it, and look for "Details" ->  "Subject Name" -> "Organization". Let me know if "Organizational Unit" is there as well.

I don't know how many of the details on the certificate are intended to be private, so don't send a screenshot or anything, just in case!

**Comment by chinedufn** [comment]
My steps:

Opened Keychain.app -> Searched "develop" -> Checked every certificate

It looks like all of my certificates have the organization field set.

Does it matter if the organization's name has a space in it? Otherwise, I'm not seeing anything that looks abnormal.

**Comment by francesca64** [comment]
Thanks for checking! It shouldn't matter if there's a space in it, though it does matter for it to be under "Subject Name" rather than under "Issuer".

I've pushed up some improvements (8a638e85e8bce18478c2fabc6c9f8a34cbcab00c), so if you `cargo mobile update` you should at least be able to proceed past this specific error. I've also added more logging so we can determine which specific cert is being used.

**Comment by chinedufn** [comment]
Awesome thanks so much.

Here's what I see now:

```
Detected template packs:
  [0] bevy
  [1] bevy-demo
  [2] wgpu
  [3] winit
  Enter an index for a template pack above.
Template pack (0): 2
[2021-03-09T12:54:11Z ERROR cargo_mobile::apple::teams] found cert "Safari Developer: (REDACTED) my-email@gmail.com" but failed to get organization; falling back to displaying common name
[2021-03-09T12:54:11Z ERROR cargo_mobile::apple::teams] regex failed to capture nice part of name in cert "Safari Developer: (REDACTED) my-email@gmail.com"; falling back to displaying full name
error: Failed to prompt for `apple` config
    Failed to find Apple developer teams: Missing X509 field "Organizationl Unit" (Nid(18))
```

Where `REDACTED` is really an alphanumeric all caps string.

---

It looks like it's pcking up one of my certificates that I have lying around from a consulting job where I needed to deploy a Safari Mac App. I got it from the company's organization. So maybe this is some sort of permissions thing? The certificate's name that it is trying to use is `3rd Party Mac Developer Installer COMPANYNAME, INC (REDACTED)` where `REDACTED` is the same string as in the above error message. The organization is under the `Subject Name`.

---

Is there an easy way for me to make a new certificate that works properly and have cargo mobile use that?

**Comment by francesca64** [comment]
I've pushed a change that makes failure to parse certs non-fatal: 6231e9380e0a7d85e9fa42c7e8dd8b48c74ce20c

So if there are any certs that we're able to use, we'll proceed to find those instead of choking on any that we can't.

If you need a new cert, the easiest way should be to go to Xcode -> Preferences -> Accounts -> Manage Certificates.

<img width="935" alt="Screen Shot 2021-03-16 at 14 43 23" src="https://user-images.githubusercontent.com/2096580/111384162-6a1cf180-8666-11eb-93ce-397e4e9a455e.png">

**Comment by chinedufn** [comment]
Works for me and I can now initialize and run a WebGPU app. Thanks for your help. I was lost but now I am found.

Cheers and thanks.
