### ISSUE TITLE
About Linux Support, what should these functions do?

### ISSUE THREAD

**Issue by trindadegm** [BrainiumLLC/cargo-mobile#3]
I was able to get the examples to run on Linux+Android on a fork of this repository. The thing is that I have some doubts about certain functions. I have no mac, so I'm really not sure on what they look like when working.

So those are `detect_editor` and `open_file` on `src/os/macos/mod.rs`. Now, the names seem intuitive enough but I have no idea of what CFURL is. Yet more important that that, I do not know of any Linux equivalent. Thankfully they are not "required" to make `cargo mobile init`, `cargo android run` or `cargo android open`. So most stuff works fine. Obviously apple won't work anyway so I didn't try any of those.

The `open_file_with` function on  that same file is used to open Android Studio... by passing `Android Studio` on the string. That is currently working in a very ugly manner, as AFAIK there is no reliable way to launch applications by their name in a way that works in all Linux distros, but I may be wrong. Currently I just place a `Android Studio` link to `studio.sh` (from the actual installation) on my local path. It's ugly but it works. I'm still thinking on how to solve this problem properly. I was avoiding touching anything outside the "os" folder (had to add some `#[cfg]` stuff though).

The bevy-demo displays fine, the "ball" moving and stuff. The triangle also displays. Winit, well, creates the black window and gets the touch events. On the bevy sprite however, I can't see the sprite, I might try on a Samsung tablet later. I hope I can find the problem.

**Comment by francesca64** [comment]
Thanks so much for spearheading this!

`detect_editor` specifically detects the default editor for .rs files, and `open_file`... well, yknow, opens the file with whatever program `Application` represents. `CFURL` is just an implementation detail of how we interact with the macOS's API for opening files.

The reason there's a split between detecting the editor and opening files is because what we're opening is typically a directory, but we want to open it using the user's default editor for Rust. Convenient CLI tools like `open` on macOS and `xdg-open` on Linux don't tend to be designed for this use-case, sadly...

For `detect_editor`, it looks like [`xdg-mime`](https://unix.stackexchange.com/a/297941) is the way to go, and gives you the filename of the desktop entry for that application. Judging from [the spec](https://specifications.freedesktop.org/menu-spec/latest/ar01s02.html), you can find the path for that entry by iterating over the paths in the `XDG_DATA_DIRS` env var, and then checking if that filename exists within the `applications` subdir of that directory. After you've found it, you'd parse the entry using [this crate](https://crates.io/crates/freedesktop_entry_parser), or a regex if that crate doesn't work out for some reason. I believe the [`Exec`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html) field is what we're looking for, which specifies how to launch the application. The value of `Exec` is what you'd store in `Application`.
 
As for `open_file`, constructing the command is optimistically as easy as using `bossy::Command::impure_parse` on the value of `Exec` (`impure_parse` should take care of parsing any arguments that might be part of `Exec`), and then using `with_arg` to add the passed path as an argument. 

As for finding applications by name... a cursory search didn't give me any convenient leads. Desktop entries also have a [`Name`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) field, so (unfortunately) the correct way to do this might just be to iterate through the desktop entries to check if the name matches. On the bright side, most of the logic is shared with `detect_editor`!

> On the bevy sprite however, I can't see the sprite

I believe Bevy doesn't currently support assets on Android? In any case, I get the same behavior on my end.

Thanks again!

**Comment by ndarilek** [comment]
Wondering what the progress on this fork is?

Windows isn't supported yet, and I'm wondering if the Linux support might get us partway there? Failing that, I can run in WSL for the time being.

Thanks.

**Comment by trindadegm** [comment]
The pull request is on #5. On this last five or so days I really did not do anything on that branch, until today, but everything is implemented. I just hope everything is all right. It is currently begin reviewed.

If you really want to use it now, it shouldn't be hard. The most recent changes are being made on `fix_conflicts` branch. For now you may clone [that  fork](https://github.com/trindadegm/cargo-mobile), switch to the branch `fix_conflicts`, and run this inside the directory:
```
cargo install --path .
```
Which is basically: "install the crate from this very directory". It will install it at the default installation directory, `.cargo`.

You can tell me if anything does not work.

**Comment by francesca64** [comment]
#5 has merged!
